name: build64

on: workflow_dispatch

jobs:
  GenerateWinStaticBinaries:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4.2.0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python --version
    - name: setup msvc
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: 'amd64'
    - name: Clone Qt repo and its submodules
      run: |
        # Clone Qt6 repo
        cd ..
        git clone https://code.qt.io/qt/qt5.git -b 6.7.3
        cd qt5
        perl init-repository -f --module-subset=all
        cd ..
    - name: Compile static Qt version
      run: |
        # Create shadow build folder
        cd ..
        mkdir qt6_shadow
        cd qt6_shadow
        # Setup the compiler
        # Configure Qt6
        ..\qt5\configure.bat -release -static -static-runtime -no-pch -optimize-size -platform win32-msvc -prefix "..\Qt6_binaries" -no-feature-accessibility -confirm-license -- -DFEATURE_cxx20=ON
        cmake --build . --parallel 4
        cmake --install .
    - name: Package binaries
      run: |
          # Create archive of the pre-built Qt binaries
          7z a qt6_673_static_64.zip ..\Qt6_binaries
          tar -cf qt6_673_static_64.tar ..\Qt6_binaries
    - name: Upload tar
      uses: actions/upload-artifact@v4.4.0
      with:
        overwrite: true
        name: qt6_673_static_64.tar
        path: qt6_673_static_64.tar
    - name: Upload zip
      uses: actions/upload-artifact@v4.4.0
      with:
        overwrite: true
        name: qt6_673_static_64
        path: qt6_673_static_64.zip
    - name: Release
      uses: softprops/action-gh-release@v2.0.8
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: qt6_673_static_64.zip
